apiVersion: v1
kind: Secret
metadata:
  name: camel-config
type: Opaque
stringData:
  application.properties: |
    enricher.topic.warehouse-lis-in.direction=in
    enricher.topic.warehouse-lis-in.warehouse=LIS
    enricher.topic.warehouse-lis-out.direction=out
    enricher.topic.warehouse-lis-out.warehouse=LIS
    enricher.topic.warehouse-ath-in.direction=in
    enricher.topic.warehouse-ath-in.warehouse=ATH
    enricher.topic.warehouse-ath-out.direction=out
    enricher.topic.warehouse-ath-out.warehouse=ATH
    enricher.sink-topic=headquarter-location-records
    enricher.kafka-brokers=headquarter-kafka-bootstrap:9092
    enricher.kafka.security-protocol=SASL_PLAINTEXT
    enricher.kafka.sasl-mechanism=SCRAM-SHA-512
